substitutions:
  name: ant-bms

esphome:
  name: ${name}
  platform: ESP32
  board: esp-wrover-kit

external_components:
  - source: github://syssi/esphome-ant-bms@main
    refresh: 0s
#  - source: components
#    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:
  level: VERY_VERBOSE
  logs:
    api.service: WARN
    ota: WARN
    wif: WARN
    sensor: DEBUG

uart:
  id: uart0
  baud_rate: 19200
  rx_buffer_size: 384
  tx_pin: GPIO14
  rx_pin: GPIO4
  debug:
    direction: BOTH

ant_modbus:
  id: modbus0
  uart_id: uart0

ant_bms:
  id: bms0
  ant_modbus_id: modbus0

sensor:
  - platform: ant_bms
    capacity_remaining:
      name: "${name} capacity remaining"
    soc:
      name: "${name} soc"
    total_voltage:
      name: "${name} total voltage"
